# ***PANDAS FUNDAMENTALS***

**Pandas** handle
1. Data Preprocessing : Handle Missing Values
2. Data Cleaning : Remove Duplicates and Fix inconsistencies
3. Data Transformation : Filter, sort, Modify data
4. Data Visualization : Represents Data Graphically

In [ ]:
import pandas as pd
print(pd.__version__)

**SERIES | DATA FRAMES**

**SERIES** : One Cloumn

**DATA FRAMES** : Entire Table

In [ ]:
import pandas as pd
ages = pd.Series([25,30,45,38])
print(ages)

In [ ]:
# We can Create Custom Tables
ages = pd.Series([25,30,45],
                 index=["Customer_1","Customer_2","Customer_3"])
print(ages)

In [ ]:
# DATA FRAMES
data = {
    "name":["Alice","Bob","Charlie"],
    "age":[25,35,45],
    "city":["Bangalore","Delhi","Mumbai"],
    "churn":[0,1,0]
}

# Create a Data Frame
df = pd.DataFrame(data) # Think DATA FRAME as as FEATURES (input)
print(df)
# FOR ML : ROWS = Samples/Observations & CLOUMNS = FEATURES /VARIABLES

In [11]:
#from sqlite3 import Connection

# Loading Real Data
#df = pd.read_csv("customer.csv") # Read from CSV file
df= pd.read_excel("customer.xlsx") # Read from XLSX file
#df = pd.read_json("Customer.json") # Read from JSON
#df= pd.read_sql(query, Connection) # Read form DATABASE with CONNECTIONS

In [18]:
# Different Operations
print(df.head()) # First Five Rows
print(df.tail()) # Last 5 Rows
print(df.sample(5)) # Random Records
# print(df.shape()) # Rows X Columns

# -------------

# df.columns
# df.dtypes
# df.info
# df.describe() # Statistical Summary
# df.describe(include="object") # Categorical Summary

   customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No
1  5575-GNVDE    Male              0      No         No      34          Yes
2  3668-QPYBK    Male              0      No         No       2          Yes
3  7795-CFOCW    Male              0      No         No      45           No
4  9237-HQITU  Female              0      No         No       2          Yes

      MultipleLines InternetService OnlineSecurity  ... StreamingTV  \
0  No phone service             DSL             No  ...          No
1                No             DSL            Yes  ...          No
2                No             DSL            Yes  ...          No
3  No phone service             DSL            Yes  ...          No
4                No     Fiber optic             No  ...          No

  StreamingMovies        Contract PaperlessBilling              PaymentMethod  \
0              No  Month-to-month              Yes           Electronic check
1              No        One year               No               Mailed check
2              No  Month-to-month              Yes               Mailed check
3              No        One year               No  Bank transfer (automatic)
4              No  Month-to-month              Yes           Electronic check

  MonthlyCharges TotalCharges numAdminTickets  numTechTickets Churn
0          29.85        29.85               0               0    No
1          56.95       1889.5               0               0    No
2          53.85       108.15               0               0   Yes
3          42.30      1840.75               0               3    No
4          70.70       151.65               0               0   Yes

[5 rows x 23 columns]
      customerID  gender  SeniorCitizen Partner Dependents  tenure  \
7038  6840-RESVB    Male              0     Yes        Yes      24
7039  2234-XADUH  Female              0     Yes        Yes      72
7040  4801-JZAZL  Female              0     Yes        Yes      11
7041  8361-LTMKD    Male              1     Yes         No       4
7042  3186-AJIEK    Male              0      No         No      66

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
7038          Yes               Yes             DSL            Yes  ...
7039          Yes               Yes     Fiber optic             No  ...
7040           No  No phone service             DSL            Yes  ...
7041          Yes               Yes     Fiber optic             No  ...
7042          Yes                No     Fiber optic            Yes  ...

     StreamingTV StreamingMovies        Contract PaperlessBilling  \
7038         Yes             Yes        One year              Yes
7039         Yes             Yes        One year              Yes
7040          No              No  Month-to-month              Yes
7041          No              No  Month-to-month              Yes
7042         Yes             Yes        Two year              Yes

                  PaymentMethod MonthlyCharges TotalCharges numAdminTickets  \
7038               Mailed check          84.80       1990.5               0
7039    Credit card (automatic)         103.20       7362.9               0
7040           Electronic check          29.60       346.45               0
7041               Mailed check          74.40        306.6               0
7042  Bank transfer (automatic)         105.65       6844.5               2

      numTechTickets Churn
7038               0    No
7039               5    No
7040               0    No
7041               0   Yes
7042               0    No

[5 rows x 23 columns]
      customerID  gender  SeniorCitizen Partner Dependents  tenure  \
5412  3733-UOCWF    Male              1     Yes         No      61
3165  1834-WULEG    Male              0     Yes        Yes      24
196   9178-JHUVJ    Male              0     Yes        Yes      24
6008  4451-RWASJ    Male              0     Yes        Yes      15
2142  4223-BKEOR  Female              0      No        Yes      21

     PhoneService MultipleLines InternetService       OnlineSecurity  ...  \
5412          Yes           Yes     Fiber optic                   No  ...
3165          Yes            No              No  No internet service  ...
196           Yes           Yes              No  No internet service  ...
6008          Yes            No              No  No internet service  ...
2142          Yes            No             DSL                  Yes  ...

              StreamingTV      StreamingMovies  Contract PaperlessBilling  \
5412                   No                   No  One year              Yes
3165  No internet service  No internet service  One year               No
196   No internet service  No internet service  Two year              Yes
6008  No internet service  No internet service  One year              Yes
2142                   No                  Yes  One year               No

                  PaymentMethod MonthlyCharges TotalCharges numAdminTickets  \
5412  Bank transfer (automatic)          85.55      5251.75               0
3165               Mailed check          20.25       439.75               2
196   Bank transfer (automatic)          24.10        587.4               0
6008               Mailed check          19.50       239.75               0
2142               Mailed check          64.85       1336.8               0

      numTechTickets Churn
5412               0    No
3165               0    No
196                0    No
6008               1    No
2142               0    No

[5 rows x 23 columns]

In [22]:
print(df["gender"])# SIngle Column
# df["age","tenure"] # Multiple Columns
print(type([df["gender"]])) # Series
# type(df["gender","tenure"]) # Data Frames

0       Female
1         Male
2         Male
3         Male
4       Female
         ...
7038      Male
7039    Female
7040    Female
7041      Male
7042      Male
Name: gender, Length: 7043, dtype: object
<class 'list'>

**`loc vs iloc`**

In [24]:
df.loc[0:3,
       ["gender","SeniorCitizen"]
       ]

   gender  SeniorCitizen
0  Female              0
1    Male              0
2    Male              0
3    Male              0

In [25]:
df.iloc[0] # select by integer position
df.iloc[0:3] # first 3 rows
df.iloc[0:3,1:4] # specific Rows and Columns

   gender  SeniorCitizen Partner
0  Female              0     Yes
1    Male              0      No
2    Male              0      No

In [26]:
df.isna()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,numAdminTickets,numTechTickets,Churn
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7039,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7040,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7041,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7042,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [27]:
df.isna().sum() # Count Missing Values Per Column

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
numAdminTickets     0
numTechTickets      0
Churn               0
dtype: int64

In [28]:
missing_pct = (
    df.isna().mean() * 100
)
print(missing_pct)

customerID          0.0
gender              0.0
SeniorCitizen       0.0
Partner             0.0
Dependents          0.0
tenure              0.0
PhoneService        0.0
MultipleLines       0.0
InternetService     0.0
OnlineSecurity      0.0
OnlineBackup        0.0
DeviceProtection    0.0
TechSupport         0.0
StreamingTV         0.0
StreamingMovies     0.0
Contract            0.0
PaperlessBilling    0.0
PaymentMethod       0.0
MonthlyCharges      0.0
TotalCharges        0.0
numAdminTickets     0.0
numTechTickets      0.0
Churn               0.0
dtype: float64

In [29]:
df.dropna() # Dropping Missing Values

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,numAdminTickets,numTechTickets,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0,0,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,No,One year,No,Mailed check,56.95,1889.5,0,0,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,0,0,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0,3,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,0,0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,0,0,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,0,5,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,0,0,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,0,0,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,2,0,No

In [30]:
df.dropna(axis=1)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,numAdminTickets,numTechTickets,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0,0,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,No,One year,No,Mailed check,56.95,1889.5,0,0,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,0,0,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0,3,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,0,0,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,0,0,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,0,5,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,0,0,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,0,0,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,2,0,No

In [31]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
7038    False
7039    False
7040    False
7041    False
7042    False
Length: 7043, dtype: bool

In [32]:
df.duplicated().sum()

np.int64(0)